version: 1.0.{build}
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: minimal
before_deploy:
- ps: |
    Write-host "Checking is snupkg files were created..." -foregroundcolor cyan
    $expectedPackageName = "SnupkgTestNetFramework.$env:appveyor_build_version.snupkg"
    if (($artifacts.values | Where-Object {$_.path.EndsWith($expectedPackageName)}) -eq $null) {throw "$($expectedPackageName).snupkg package was not created"}
    $expectedPackageName = "SnupkgTestNetStandard.$env:appveyor_build_version.snupkg"
    if (($artifacts.values | Where-Object {$_.path.EndsWith($expectedPackageName)}) -eq $null) {throw "$($expectedPackageName).snupkg package was not created"}
deploy:
- provider: NuGet
  api_key:
    secure: 5SIE4/3x2dcjxQy4PYbGLznXnUbalpTrey+eL0TqNKFHnWDyX9O/PuBfb0jaKYMz
